### ISSUE TITLE
Can't login with already-registered user nor can i register new users

### ISSUE THREAD

**Issue by kamovag** [nzbszb/usn#1]
I'm using Xampp/Lampp stack on Ubuntu and seems like no matter how much i try, i can't login, not with the already registered/verified users in the mysql dump, nor when i try to add & verify new users through the phpmyadmin. 
Would appreciate to know what i'm doing wrong.
Cheers.

**Comment by nzbszb** [comment]
sorry for not noticing your issue. In reality the attributes of demo tables of the database were used to register the user while verifying authenticity. Also you need to either up your project in live server for verification mail or modify your xampp/lampp sendmail for the mail account connection or check the verification code from the db. This project was for existing authorized students and that time I wasn't that skilled. So most of it was done using PHP & Jquery.
